server:
  port: 8088
  servlet:
    context-path: /es
spring:
  application:
    name: Elastic Search App
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  elasticsearch:
    uris: localhost:9200
    username: elastic
    password: elastic!

logging:
  pattern:
    console: "%d %-5level [%thread] %-5p %c{1}:%L %logger : %msg%n"
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.rdas.es:  DEBUG